[tool.poetry]
authors=["Zach Cobell"]
name="add_numbers"
description="none"
version = "0.0.1"
packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
